spring:
  profiles:
    active: prod

  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f0d95e2acbedd038ac6428aa718c8297
            client-secret: odrjdeKUqUGpvEFr2QrXXaBSxRfvHYu5
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
          naver:
            client-id: _czw6R2LOmQtRgckEZ11
            client-secret: mM2bFYjBeu
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: 1074727399716-tookoele358tge4mn7v7qpa8bkrrcu29.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
